language: ruby
rvm:
  - 2.0.0
script: bundle exec rake
before_install:
  - gem update --system
services:
  - redis-server
notifications:
  email: false
  webhooks:
    urls:
      - https://lita-freenode.herokuapp.com/travis
